---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-app-a-run-
  annotations:
    chains.tekton.dev/signed: 'true'
  namespace: {{ .Values.namespacePermissions.user }}-dev
  labels:
    tekton.dev/pipeline: build-app
spec:
  params:
    - name: app
      value: app-a
  pipelineRef:
    name: build-app
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: source
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-basic-auth
      secret:
        secretName: git-basic-auth
