apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitops-service-mesh-admin.yaml
  - gitops-argocd-admin.yaml
  - gitops-admin-admin.yaml
  - gitops-service-mesh-memberrolls-admin.yaml
  - otq-ocp1-login-challenge.yaml

components:
  - ../../components/resolutionrequests-cleaner/
