apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhsc-post-configuration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhsc-post-configuration
subjects:
- kind: ServiceAccount
  name: rhsc-post-configuration
