apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhsc-post-configuration

resources:
 - namespace.yaml
 - rolebinding-argocd.yaml
 - serviceaccount.yaml
 - clusterrole.yaml
 - clusterrolebinding.yaml
 - configmap.yaml
 - job.yaml
