---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nginx-example-app
  namespace: {{ .Values.namespacePermissions.user }}-dev
spec:
  to:
    kind: Service
    name: nginx-example-app
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
