apiVersion: v1
kind: Service
metadata:
  name: nginx-example-app
  namespace: {{ .Values.namespacePermissions.user }}-app
spec:
  selector:
    app: nginx-example-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
