apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - central.yaml
  - cluster-init.yaml
  - console-link.yaml
  - declarative-oauth.yaml
  - rbac.yaml
  - secured-cluster.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - job.yaml

namespace: stackrox