apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhacs-post-configuration
  namespace: rhacs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhacs-post-configuration
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consolelinks
  verbs:
  - "*"
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhacs-post-configuration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhacs-post-configuration
subjects:
- kind: ServiceAccount
  name: rhacs-post-configuration
