
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-nginx-example-fixme
  namespace: {{ .Values.namespacePermissions.user }}-gitops
spec:
  destination:
    namespace: {{ .Values.namespacePermissions.user }}-apps
    server: https://kubernetes.default.svc
  source:
    path: nginx-example-fixme
#    repoURL: https://gitea.{openshift_cluster_ingress_domain}/{{ .Values.namespacePermissions.user }}/gitops.git
    repoURL: https://github.com/sa-mw-dach/microservice-introduction-gitops.git
    targetRevision: summit
  project: default